### ISSUE TITLE
No Chrome installations found

### ISSUE THREAD

**Issue by Ailsa98** [thlorenz/unity-pdf-docs#2]
Failed to launch chrome ChromeNotInstalledError
    at new LauncherError (/usr/local/lib/node_modules/unity-pdf-docs/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromeNotInstalledError (/usr/local/lib/node_modules/unity-pdf-docs/node_modules/chrome-launcher/dist/utils.js:66:9)
    at Launcher.<anonymous> (/usr/local/lib/node_modules/unity-pdf-docs/node_modules/chrome-launcher/dist/chrome-launcher.js:145:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/unity-pdf-docs/node_modules/chrome-launcher/dist/chrome-launcher.js:9:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  message: 'No Chrome installations found.',
  code: 'ERR_LAUNCHER_NOT_INSTALLED'
}

**Comment by Ailsa98** [comment]
I tried export CHROME_PATH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' but it does not work.
